[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Show an Iridescent Ace to confirm Frozen Overhaul is Active
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "replace_card.states.visible = false"
position = "before"
payload = "replace_card:set_edition('e_frover_iridescent', true, true)"
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "replace_card.states.visible = false"
position = "before"
payload = "replace_card:set_ability('m_glass', true, true)"
match_indent = true
overwrite = false

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/overrides.lua"]'
pattern = '''if _key == "wheel_of_fortune" or _key == "aura" then -- set base game edition polling'''
position = 'after'
match_indent = true
payload = '''
_options[#_options+1] = "e_frover_iridescent"
'''